/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#c7ecca",
        "on-surface": "#1b1c19",
        "on-secondary-fixed-variant": "#594325",
        "surface-container-high": "#eae8e3",
        "on-tertiary-container": "#c4c9b2",
        "background": "#fbf9f4",
        "tertiary-fixed-dim": "#c4c9b1",
        "surface-container-low": "#f5f3ee",
        "outline-variant": "#c2c8bf",
        "on-secondary-container": "#785e3e",
        "on-background": "#1b1c19",
        "on-secondary-fixed": "#291801",
        "on-error-container": "#93000a",
        "inverse-surface": "#30312e",
        "primary": "#23422a",
        "surface-container": "#f0eee9",
        "on-primary-container": "#acd0af",
        "surface-bright": "#fbf9f4",
        "inverse-on-surface": "#f2f1ec",
        "on-primary": "#ffffff",
        "secondary": "#735a3a",
        "primary-container": "#3a5a40",
        "surface-variant": "#e4e2dd",
        "on-tertiary": "#ffffff",
        "surface": "#fbf9f4",
        "primary-fixed-dim": "#abd0af",
        "on-tertiary-fixed-variant": "#444937",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffddb6",
        "tertiary-fixed": "#e0e5cc",
        "surface-container-highest": "#e4e2dd",
        "surface-tint": "#45664b",
        "secondary-container": "#fddab2",
        "on-primary-fixed": "#02210c",
        "on-tertiary-fixed": "#191d0e",
        "secondary-fixed-dim": "#e2c19b",
        "tertiary": "#393e2c",
        "on-surface-variant": "#424842",
        "error-container": "#ffdad6",
        "tertiary-container": "#505542",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#2e4e35",
        "inverse-primary": "#abd0af",
        "outline": "#727971",
        "surface-dim": "#dbdad5"
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
};
